name: Test, build & deploy client

on:
#   push:
#     branches: 
#       - dev
#     paths:
#       - 'client/**'
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
      
      #
      # Install Node.js v16
      #
      - name: Install Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      #
      # Install dependencies
      #
      - name: Install dependencies
        run: npm install

      #
      # Test the application before build
      #
      - name: Test the application
        run: echo test should be placed here
        
      #
      # Build the application
      #
      - name: Build the React application
        run: npm run build
