name: Test, build & deploy client

on:
  push:
    branches: 
      - dev
    paths:
      - 'client/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: client

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
      
      - name: Install Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        
      - name: Build the React application
        run: npm run build

  # test:
  #   runs-on: ubuntu-latest

  #   steps:

  #     - name: Test the application
  #       run: echo test should be placed here

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy ./build to S3 bucket
        run: aws s3 sync ./build/ s3://${{ secrets.AWS_DEV_BUCKET_NAME }} --delete